# ChatTLM: the device application and its host test suite.
#
# WHY THIS FILE EXISTS. Until it did, build/chattlm.tns and every build/test_* binary existed only
# because someone had typed a fifteen-file cross-compile line into a shell. Nothing in the repo
# produced them -- which meant tools/eval/run_gates.sh ran ./build/test_* that nothing built, so a
# fresh clone failed the gates with "not built" and a typo in the link line was invisible until it
# was not.
#
#   make            host tests + the device binary
#   make tests      host only, no toolchain needed
#   make device     build/chattlm.tns
#   make check      build the tests, then run the full gate suite
#   make clean
#
# The device target needs the Ndless toolchain, which lives in the repo:
#   vendor/Ndless/ndless-sdk/{bin,toolchain/install/bin}
# tools/build_toolchain_macos.sh names the prefix if it is missing.

ROOT      := $(CURDIR)
SDK       := $(ROOT)/vendor/Ndless/ndless-sdk
DEVPATH   := $(SDK)/bin:$(SDK)/toolchain/install/bin:$(PATH)
BUILD     := build

CC        ?= cc
HOSTFLAGS := -O2 -DTLM_HOST -Isrc/store -Itools/eval
NSPFLAGS  := -O2 -Wall -std=gnu99 -marm -mcpu=arm926ej-s -Iinclude -Isrc/store -Isrc -Itools/eval

# ---- sources ---------------------------------------------------------------------------------
# The evaluator's CORE, verbatim from tools/eval/Makefile. Kept in step by hand; if that list
# changes this one must too, which is noted because a silent divergence would show up as a link
# error at best and a stale evaluator at worst.
EVAL_CORE := $(addprefix tools/eval/, fmt.c ast.c units.c parser.c numeric.c deriv.c solve.c \
                                      literal.c integrate.c stat.c dispatch.c)

APP_SRC   := src/store/app.c src/store/gfx.c src/store/loader.c src/store/assemble.c \
             src/store/tokenizer.c src/store/picker.c src/store/toolrun.c src/store/chatstore.c

DEV_SRC   := src/store/device_app.c $(APP_SRC) src/runq_nspire.c src/nspire.c include/nspire_screen.c

# app.c is #included by the suites that exercise its statics, so it is NOT linked separately there.
HOST_LINK := src/store/gfx.c src/store/chatstore.c $(BUILD)/hoststub.o

# ---- host tests ------------------------------------------------------------------------------
# Two groups, because they differ in what they link. INCLUDES_APP suites #include app.c directly to
# reach its file-scope state; the others link toolrun.c and the evaluator.
TESTS_APP  := test_search test_span test_exit test_bubble test_notation test_theme test_select
TESTS_EVAL := test_toolrun
TESTS_PLAIN:= test_chatstore test_ckpt
TESTS      := $(TESTS_APP) $(TESTS_EVAL) $(TESTS_PLAIN)

.PHONY: all tests device check clean
all: tests device

tests: $(addprefix $(BUILD)/,$(TESTS)) $(BUILD)/render_app

$(BUILD):
	@mkdir -p $(BUILD)

# The host has no wall clock to offer the UI and no model to generate from. Both stubs return the
# honest "nothing here" answer rather than a plausible default -- see app.h on app_clock_hour.
$(BUILD)/hoststub.c: | $(BUILD)
	@printf '%s\n' \
	  '/* Host stubs. Generated by the Makefile; see app.h on why these return nothing. */' \
	  'void app_request(const char *q, const char *r) { (void)q; (void)r; }' \
	  'int  app_clock_hour(void) { return -1; }' > $@

$(BUILD)/hoststub.o: $(BUILD)/hoststub.c
	$(CC) $(HOSTFLAGS) -c $< -o $@

# These suites #include src/store/app.c to reach its file-scope state, so app.c and app.h are real
# prerequisites. Without them a palette-only edit left build/test_theme "up to date" and the gate
# passed on a stale binary -- a suite that cannot see your change is worse than no suite.
$(addprefix $(BUILD)/,$(TESTS_APP)): $(BUILD)/%: tools/eval/%.c $(APP_SRC) src/store/app.h src/store/font_data.h $(BUILD)/hoststub.o | $(BUILD)
	$(CC) $(HOSTFLAGS) -o $@ $< $(HOST_LINK) -lm

$(BUILD)/render_app: tools/eval/render_app.c $(APP_SRC) src/store/app.h $(BUILD)/hoststub.o | $(BUILD)
	$(CC) $(HOSTFLAGS) -o $@ $< $(HOST_LINK) src/store/toolrun.c $(EVAL_CORE) -lm

$(BUILD)/test_toolrun: tools/eval/test_toolrun.c src/store/toolrun.c src/store/toolrun.h | $(BUILD)
	$(CC) $(HOSTFLAGS) -o $@ $< src/store/toolrun.c $(EVAL_CORE) -lm

$(BUILD)/test_chatstore: tools/eval/test_chatstore.c src/store/chatstore.c src/store/chatstore.h | $(BUILD)
	$(CC) $(HOSTFLAGS) -o $@ $< src/store/chatstore.c src/store/gfx.c -lm

# Compiles runq_nspire.c on the HOST, which is the point: the loader that runs on the calculator is
# the one under test, not a reimplementation of its rules.
$(BUILD)/test_ckpt: tools/eval/test_ckpt.c src/runq_nspire.c | $(BUILD)
	$(CC) $(HOSTFLAGS) -DFIXED_GS=96 -o $@ $< -lm

# ---- device ----------------------------------------------------------------------------------
device: $(BUILD)/chattlm.tns

$(BUILD)/chattlm.tns: $(DEV_SRC) $(EVAL_CORE) | $(BUILD)
	@command -v nspire-gcc >/dev/null 2>&1 || export PATH="$(DEVPATH)"; \
	 PATH="$(DEVPATH)"; export PATH; \
	 nspire-gcc $(NSPFLAGS) -o $(BUILD)/chattlm.elf $(DEV_SRC) $(EVAL_CORE) -lm && \
	 genzehn --input $(BUILD)/chattlm.elf --output $(BUILD)/chattlm.zehn --name chattlm && \
	 make-prg $(BUILD)/chattlm.zehn $@ && \
	 rm -f $(BUILD)/chattlm.zehn && \
	 echo "  $@  $$(wc -c < $@ | tr -d ' ') bytes"

# ---- gates -----------------------------------------------------------------------------------
# Builds first, so "not built" can never be mistaken for a passing suite.
check: tests
	@bash tools/eval/run_gates.sh

clean:
	rm -f $(addprefix $(BUILD)/,$(TESTS)) $(BUILD)/render_app $(BUILD)/hoststub.[co] \
	      $(BUILD)/chattlm.elf $(BUILD)/chattlm.zehn
