#include <stdlib.h>
#include <string.h>
#include "gfx.h"
#include "font_data.h"

#ifndef TLM_HOST
#include <libndls.h>
#endif

static uint16_t *FB;
static int CX0, CY0, CX1, CY1;      /* clip rect, half-open */

void gfx_init(void) {
    FB = (uint16_t *)malloc((size_t)GFX_W * GFX_H * 2);
    gfx_clip_reset();
#ifndef TLM_HOST
    lcd_init(SCR_320x240_565);
#endif
}
void gfx_free(void) {
#ifndef TLM_HOST
    lcd_init(SCR_TYPE_INVALID);      /* hand the panel back to the OS */
#endif
    free(FB); FB = 0;
}
uint16_t *gfx_buf(void) { return FB; }

void gfx_present(void) {
#ifndef TLM_HOST
    lcd_blit(FB, SCR_320x240_565);
#endif
}

void gfx_clip(int x, int y, int w, int h) {
    CX0 = x < 0 ? 0 : x;  CY0 = y < 0 ? 0 : y;
    CX1 = x + w > GFX_W ? GFX_W : x + w;
    CY1 = y + h > GFX_H ? GFX_H : y + h;
}
void gfx_clip_reset(void) { CX0 = CY0 = 0; CX1 = GFX_W; CY1 = GFX_H; }

static inline void px(int x, int y, uint16_t c) {
    if (x < CX0 || x >= CX1 || y < CY0 || y >= CY1) return;
    FB[y * GFX_W + x] = c;
}

void gfx_clear(uint16_t c) {
    for (int i = 0; i < GFX_W * GFX_H; i++) FB[i] = c;
}
void gfx_fill(int x, int y, int w, int h, uint16_t c) {
    for (int j = y; j < y + h; j++) {
        if (j < CY0 || j >= CY1) continue;
        int a = x < CX0 ? CX0 : x, b = x + w > CX1 ? CX1 : x + w;
        uint16_t *row = FB + j * GFX_W;
        for (int i = a; i < b; i++) row[i] = c;
    }
}
void gfx_hline(int x, int y, int w, uint16_t c) { gfx_fill(x, y, w, 1, c); }
void gfx_vline(int x, int y, int h, uint16_t c) { gfx_fill(x, y, 1, h, c); }

/* Rounded rectangle. The corner test is a plain radius compare rather than a Bresenham arc:
 * at r<=12 the difference is invisible and this needs no per-corner special casing. */
void gfx_rrect(int x, int y, int w, int h, int r, uint16_t c) {
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    for (int j = 0; j < h; j++) {
        int dy = (j < r) ? (r - j) : (j >= h - r ? j - (h - r) + 1 : 0);
        int inset = 0;
        if (dy) { while (inset < r && (r - inset) * (r - inset) + dy * dy > r * r) inset++; }
        gfx_hline(x + inset, y + j, w - 2 * inset, c);
    }
}
void gfx_rrect_outline(int x, int y, int w, int h, int r, uint16_t c) {
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    for (int j = 0; j < h; j++) {
        int dy = (j < r) ? (r - j) : (j >= h - r ? j - (h - r) + 1 : 0);
        int inset = 0;
        if (dy) { while (inset < r && (r - inset) * (r - inset) + dy * dy > r * r) inset++; }
        if (j < r || j >= h - r) {
            px(x + inset, y + j, c);
            px(x + w - 1 - inset, y + j, c);
            if (j == 0 || j == h - 1) gfx_hline(x + inset, y + j, w - 2 * inset, c);
        } else {
            px(x, y + j, c);
            px(x + w - 1, y + j, c);
        }
    }
}

/* ---- text ------------------------------------------------------------------------------------
 * Glyphs are 4bpp coverage, generated by tools/mkfont.py. Blending is a per-channel lerp between
 * bg and fg in RGB565 -- no alpha buffer, because every surface this draws onto is a known flat
 * colour and compositing would cost memory the model needs. */
typedef struct { const ns_glyph *idx; int n; const unsigned char *data; int h, asc; } fontref;

static fontref fref(gfx_font f) {
    switch (f) {
    case F_UIB: { fontref r = { FONT_UIB_IDX, FONT_UIB_N, FONT_UIB_DATA, FONT_UIB_H, FONT_UIB_ASC }; return r; }
    case F_BIG: { fontref r = { FONT_BIG_IDX, FONT_BIG_N, FONT_BIG_DATA, FONT_BIG_H, FONT_BIG_ASC }; return r; }
    case F_SM:  { fontref r = { FONT_SM_IDX,  FONT_SM_N,  FONT_SM_DATA,  FONT_SM_H,  FONT_SM_ASC  }; return r; }
    case F_XS:  { fontref r = { FONT_XS_IDX,  FONT_XS_N,  FONT_XS_DATA,  FONT_XS_H,  FONT_XS_ASC  }; return r; }
    default:    { fontref r = { FONT_UI_IDX,  FONT_UI_N,  FONT_UI_DATA,  FONT_UI_H,  FONT_UI_ASC  }; return r; }
    }
}
int gfx_font_h(gfx_font f) { return fref(f).h; }

/* Minimal UTF-8 decode. The notation uses Greek and sub/superscripts, all outside ASCII. */
static const char *u8(const char *s, unsigned *cp) {
    unsigned char c = (unsigned char)*s;
    if (c < 0x80) { *cp = c; return s + 1; }
    if ((c & 0xE0) == 0xC0) { *cp = ((c & 0x1F) << 6) | (s[1] & 0x3F); return s + 2; }
    if ((c & 0xF0) == 0xE0) { *cp = ((c & 0x0F) << 12) | ((s[1] & 0x3F) << 6) | (s[2] & 0x3F); return s + 3; }
    *cp = '?'; return s + 1;
}
static const ns_glyph *find(fontref F, unsigned cp) {
    int lo = 0, hi = F.n - 1;
    while (lo <= hi) {                       /* the table is emitted in code-point order */
        int m = (lo + hi) / 2;
        if (F.idx[m].cp == cp) return &F.idx[m];
        if (F.idx[m].cp < cp) lo = m + 1; else hi = m - 1;
    }
    return 0;
}
static inline uint16_t blend(uint16_t bg, uint16_t fg, int a /*0..15*/) {
    if (a <= 0) return bg;
    if (a >= 15) return fg;
    int br = (bg >> 11) & 31, bgn = (bg >> 5) & 63, bb = bg & 31;
    int fr = (fg >> 11) & 31, fgn = (fg >> 5) & 63, fb = fg & 31;
    int r = br + (fr - br) * a / 15, g = bgn + (fgn - bgn) * a / 15, b = bb + (fb - bb) * a / 15;
    return (uint16_t)((r << 11) | (g << 5) | b);
}

/* Scale the whole frame toward a colour. The modal scrim used a 50% checkerboard, which on a
 * 320x240 panel reads as noise rather than as dimming -- and it cost 38400 gfx_fill calls. One
 * pass of blend over 76800 pixels is both correct and cheaper. */
void gfx_dim(uint16_t toward, int pct) {
    int a = pct * 15 / 100;
    for (int i = 0; i < GFX_W * GFX_H; i++) FB[i] = blend(FB[i], toward, a);
}

static int draw_glyph(int x, int y, const ns_glyph *g, fontref F, uint16_t fg, uint16_t bg) {
    const unsigned char *d = F.data + g->off;
    int bytes_per_row = (g->w + 1) / 2;
    for (int j = 0; j < F.h; j++) {
        for (int i = 0; i < g->w; i++) {
            unsigned char byte = d[j * bytes_per_row + i / 2];
            int a = (i & 1) ? (byte & 0x0F) : (byte >> 4);
            if (a) px(x + i, y + j, blend(bg, fg, a));
        }
    }
    return g->w;
}

int gfx_text(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg) {
    fontref F = fref(f);
    int x0 = x; unsigned cp;
    while (*s) {
        s = u8(s, &cp);
        const ns_glyph *g = find(F, cp);
        if (!g) continue;                     /* missing glyph draws nothing, never a box */
        x += draw_glyph(x, y, g, F, fg, bg);
    }
    return x - x0;
}
int gfx_text_w(const char *s, gfx_font f) {
    fontref F = fref(f);
    int w = 0; unsigned cp;
    while (*s) { s = u8(s, &cp); const ns_glyph *g = find(F, cp); if (g) w += g->w; }
    return w;
}
int gfx_text_ellipsis(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg, int maxw) {
    if (gfx_text_w(s, f) <= maxw) return gfx_text(x, y, s, f, fg, bg);
    fontref F = fref(f);
    int ew = gfx_text_w("...", f), w = 0, x0 = x; unsigned cp;
    const char *p = s;
    while (*p) {
        const char *nx = u8(p, &cp);
        const ns_glyph *g = find(F, cp);
        int gw = g ? g->w : 0;
        if (w + gw + ew > maxw) break;
        if (g) x += draw_glyph(x, y, g, F, fg, bg);
        w += gw; p = nx;
    }
    x += gfx_text(x, y, "...", f, fg, bg);
    return x - x0;
}

/* ONE WRAP WALK. Everything that wraps text goes through this.
 *
 * There were three copies of this loop by the time selection needed a fourth -- draw, measure-last,
 * measure-widest -- each carrying its own transcription of the break rule: longest prefix that
 * fits, broken at the last space, hard-broken when a single word exceeds the line. Every copy is a
 * place the rule can drift, and a measure that breaks differently than the draw is exactly the
 * bubble-width defect this file already carries a warning about. The public functions below are
 * thin callers; none of them reimplements the walk.
 *
 * Optional outputs, all skippable:
 *   out_last_w  width of the LAST line          (caret placement)
 *   out_widest  width of the WIDEST line        (sizing a box to its text)
 *   sel_a/sel_b BYTE range drawn on selbg       (selection highlight)
 *   probe_x/y   a pixel; out_off gets the byte offset under it, or -1
 * Returns the line count in every mode. */
static int wrap_walk(int x, int y, const char *s0, gfx_font f, uint16_t fg, uint16_t bg,
                     int maxw, int line_h, int draw,
                     int *out_last_w, int *out_widest,
                     int sel_a, int sel_b, uint16_t selbg,
                     int probe_x, int probe_y, int *out_off) {
    fontref F = fref(f);
    const char *s = s0;
    int lines = 0, widest = 0;
    if (out_off) *out_off = -1;
    while (*s) {
        const char *start = s, *p = s, *lastsp = 0;
        int w = 0; unsigned cp;
        while (*p) {
            const char *nx = u8(p, &cp);
            const ns_glyph *g = find(F, cp);
            int gw = g ? g->w : 0;
            if (w + gw > maxw) break;
            if (cp == ' ') lastsp = p;
            w += gw; p = nx;
        }
        const char *end = *p ? (lastsp ? lastsp : p) : p;
        if (end == start) end = p;            /* a single word longer than the line: hard-break */

        if (out_last_w || out_widest) {       /* width of THIS line */
            int lw = 0; const char *q = start; unsigned c2;
            while (q < end) { q = u8(q, &c2); const ns_glyph *g = find(F, c2); if (g) lw += g->w; }
            if (out_last_w) *out_last_w = lw; /* the last line to run wins */
            if (lw > widest) widest = lw;
        }

        int ly = y + lines * line_h;
        /* PROBE and DRAW share one glyph walk, so the offset reported is the offset of the glyph
         * actually painted there. Two walks would let a hit land one character off. */
        if (draw || (out_off && probe_y >= ly && probe_y < ly + line_h)) {
            int xx = x; const char *q = start;
            int on_line = out_off && probe_y >= ly && probe_y < ly + line_h;
            /* A click past the end of a line selects to the line end, not nothing. */
            if (on_line && probe_x < x) *out_off = (int)(start - s0);
            while (q < end) {
                const char *qs = q;
                q = u8(q, &cp);
                const ns_glyph *g = find(F, cp);
                int gw = g ? g->w : 0;
                if (draw && g) {
                    int off = (int)(qs - s0);
                    int sel = (sel_a >= 0 && off >= sel_a && off < sel_b);
                    /* THE HIGHLIGHT IS PAINTED, not passed. draw_glyph writes only where the glyph
                     * has alpha and uses bg purely to blend its antialiased edges, so handing it a
                     * selection colour tinted a few edge pixels and produced no visible highlight
                     * at all -- the first render of this showed none, and the pixels could not say
                     * whether the range was empty or the colour too faint.
                     *
                     * Filled per glyph rather than per run: advance widths tile exactly, so the
                     * band is continuous, and spaces inside the selection are covered without a
                     * second walk to find where the run starts and ends. line_h, not the glyph box,
                     * so consecutive lines meet with no white seam between them. */
                    if (sel) gfx_fill(xx, ly, gw, line_h, selbg);
                    draw_glyph(xx, ly, g, F, fg, sel ? selbg : bg);
                }
                if (on_line && probe_x >= xx && probe_x < xx + gw) *out_off = (int)(qs - s0);
                xx += gw;
            }
            if (on_line && probe_x >= xx) *out_off = (int)(end - s0);
        }

        lines++;
        s = end;
        while (*s == ' ') s++;
        if (lines > 200) break;               /* runaway guard */
        if (s == start) break;                /* no progress: refuse to spin */
    }
    if (out_widest) *out_widest = widest;
    return lines;
}

int gfx_text_wrap(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg,
                  int maxw, int line_h, int draw) {
    return wrap_walk(x, y, s, f, fg, bg, maxw, line_h, draw, 0, 0, -1, -1, 0, 0, -1, 0);
}
int gfx_text_wrap_ex(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg,
                     int maxw, int line_h, int draw, int *out_last_w) {
    return wrap_walk(x, y, s, f, fg, bg, maxw, line_h, draw, out_last_w, 0, -1, -1, 0, 0, -1, 0);
}
int gfx_text_wrap_w(const char *s, gfx_font f, int maxw) {
    int widest = 0;
    wrap_walk(0, 0, s, f, 0, 0, maxw, 1, 0, 0, &widest, -1, -1, 0, 0, -1, 0);
    return widest;
}
int gfx_text_wrap_sel(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg,
                      int maxw, int line_h, int sel_a, int sel_b, uint16_t selbg) {
    return wrap_walk(x, y, s, f, fg, bg, maxw, line_h, 1, 0, 0, sel_a, sel_b, selbg, 0, -1, 0);
}
int gfx_text_wrap_hit(int x, int y, const char *s, gfx_font f, int maxw, int line_h, int px, int py) {
    int off = -1;
    wrap_walk(x, y, s, f, 0, 0, maxw, line_h, 0, 0, 0, -1, -1, 0, px, py, &off);
    return off;
}
