#include <stdlib.h>
#include <string.h>
#include "gfx.h"
#include "font_data.h"

#ifndef TLM_HOST
#include <libndls.h>
#endif

static uint16_t *FB;
static int CX0, CY0, CX1, CY1;      /* clip rect, half-open */

void gfx_init(void) {
    FB = (uint16_t *)malloc((size_t)GFX_W * GFX_H * 2);
    gfx_clip_reset();
#ifndef TLM_HOST
    lcd_init(SCR_320x240_565);
#endif
}
void gfx_free(void) {
#ifndef TLM_HOST
    lcd_init(SCR_TYPE_INVALID);      /* hand the panel back to the OS */
#endif
    free(FB); FB = 0;
}
uint16_t *gfx_buf(void) { return FB; }

void gfx_present(void) {
#ifndef TLM_HOST
    lcd_blit(FB, SCR_320x240_565);
#endif
}

void gfx_clip(int x, int y, int w, int h) {
    CX0 = x < 0 ? 0 : x;  CY0 = y < 0 ? 0 : y;
    CX1 = x + w > GFX_W ? GFX_W : x + w;
    CY1 = y + h > GFX_H ? GFX_H : y + h;
}
void gfx_clip_reset(void) { CX0 = CY0 = 0; CX1 = GFX_W; CY1 = GFX_H; }

static inline void px(int x, int y, uint16_t c) {
    if (x < CX0 || x >= CX1 || y < CY0 || y >= CY1) return;
    FB[y * GFX_W + x] = c;
}

void gfx_clear(uint16_t c) {
    for (int i = 0; i < GFX_W * GFX_H; i++) FB[i] = c;
}
void gfx_fill(int x, int y, int w, int h, uint16_t c) {
    for (int j = y; j < y + h; j++) {
        if (j < CY0 || j >= CY1) continue;
        int a = x < CX0 ? CX0 : x, b = x + w > CX1 ? CX1 : x + w;
        uint16_t *row = FB + j * GFX_W;
        for (int i = a; i < b; i++) row[i] = c;
    }
}
void gfx_hline(int x, int y, int w, uint16_t c) { gfx_fill(x, y, w, 1, c); }
void gfx_vline(int x, int y, int h, uint16_t c) { gfx_fill(x, y, 1, h, c); }

/* Rounded rectangle. The corner test is a plain radius compare rather than a Bresenham arc:
 * at r<=12 the difference is invisible and this needs no per-corner special casing. */
void gfx_rrect(int x, int y, int w, int h, int r, uint16_t c) {
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    for (int j = 0; j < h; j++) {
        int dy = (j < r) ? (r - j) : (j >= h - r ? j - (h - r) + 1 : 0);
        int inset = 0;
        if (dy) { while (inset < r && (r - inset) * (r - inset) + dy * dy > r * r) inset++; }
        gfx_hline(x + inset, y + j, w - 2 * inset, c);
    }
}
void gfx_rrect_outline(int x, int y, int w, int h, int r, uint16_t c) {
    if (r * 2 > w) r = w / 2;
    if (r * 2 > h) r = h / 2;
    for (int j = 0; j < h; j++) {
        int dy = (j < r) ? (r - j) : (j >= h - r ? j - (h - r) + 1 : 0);
        int inset = 0;
        if (dy) { while (inset < r && (r - inset) * (r - inset) + dy * dy > r * r) inset++; }
        if (j < r || j >= h - r) {
            px(x + inset, y + j, c);
            px(x + w - 1 - inset, y + j, c);
            if (j == 0 || j == h - 1) gfx_hline(x + inset, y + j, w - 2 * inset, c);
        } else {
            px(x, y + j, c);
            px(x + w - 1, y + j, c);
        }
    }
}

/* ---- text ------------------------------------------------------------------------------------
 * Glyphs are 4bpp coverage, generated by tools/mkfont.py. Blending is a per-channel lerp between
 * bg and fg in RGB565 -- no alpha buffer, because every surface this draws onto is a known flat
 * colour and compositing would cost memory the model needs. */
typedef struct { const ns_glyph *idx; int n; const unsigned char *data; int h, asc; } fontref;

static fontref fref(gfx_font f) {
    switch (f) {
    case F_UIB: { fontref r = { FONT_UIB_IDX, FONT_UIB_N, FONT_UIB_DATA, FONT_UIB_H, FONT_UIB_ASC }; return r; }
    case F_BIG: { fontref r = { FONT_BIG_IDX, FONT_BIG_N, FONT_BIG_DATA, FONT_BIG_H, FONT_BIG_ASC }; return r; }
    default:    { fontref r = { FONT_UI_IDX,  FONT_UI_N,  FONT_UI_DATA,  FONT_UI_H,  FONT_UI_ASC  }; return r; }
    }
}
int gfx_font_h(gfx_font f) { return fref(f).h; }

/* Minimal UTF-8 decode. The notation uses Greek and sub/superscripts, all outside ASCII. */
static const char *u8(const char *s, unsigned *cp) {
    unsigned char c = (unsigned char)*s;
    if (c < 0x80) { *cp = c; return s + 1; }
    if ((c & 0xE0) == 0xC0) { *cp = ((c & 0x1F) << 6) | (s[1] & 0x3F); return s + 2; }
    if ((c & 0xF0) == 0xE0) { *cp = ((c & 0x0F) << 12) | ((s[1] & 0x3F) << 6) | (s[2] & 0x3F); return s + 3; }
    *cp = '?'; return s + 1;
}
static const ns_glyph *find(fontref F, unsigned cp) {
    int lo = 0, hi = F.n - 1;
    while (lo <= hi) {                       /* the table is emitted in code-point order */
        int m = (lo + hi) / 2;
        if (F.idx[m].cp == cp) return &F.idx[m];
        if (F.idx[m].cp < cp) lo = m + 1; else hi = m - 1;
    }
    return 0;
}
static inline uint16_t blend(uint16_t bg, uint16_t fg, int a /*0..15*/) {
    if (a <= 0) return bg;
    if (a >= 15) return fg;
    int br = (bg >> 11) & 31, bgn = (bg >> 5) & 63, bb = bg & 31;
    int fr = (fg >> 11) & 31, fgn = (fg >> 5) & 63, fb = fg & 31;
    int r = br + (fr - br) * a / 15, g = bgn + (fgn - bgn) * a / 15, b = bb + (fb - bb) * a / 15;
    return (uint16_t)((r << 11) | (g << 5) | b);
}

/* Scale the whole frame toward a colour. The modal scrim used a 50% checkerboard, which on a
 * 320x240 panel reads as noise rather than as dimming -- and it cost 38400 gfx_fill calls. One
 * pass of blend over 76800 pixels is both correct and cheaper. */
void gfx_dim(uint16_t toward, int pct) {
    int a = pct * 15 / 100;
    for (int i = 0; i < GFX_W * GFX_H; i++) FB[i] = blend(FB[i], toward, a);
}

static int draw_glyph(int x, int y, const ns_glyph *g, fontref F, uint16_t fg, uint16_t bg) {
    const unsigned char *d = F.data + g->off;
    int bytes_per_row = (g->w + 1) / 2;
    for (int j = 0; j < F.h; j++) {
        for (int i = 0; i < g->w; i++) {
            unsigned char byte = d[j * bytes_per_row + i / 2];
            int a = (i & 1) ? (byte & 0x0F) : (byte >> 4);
            if (a) px(x + i, y + j, blend(bg, fg, a));
        }
    }
    return g->w;
}

int gfx_text(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg) {
    fontref F = fref(f);
    int x0 = x; unsigned cp;
    while (*s) {
        s = u8(s, &cp);
        const ns_glyph *g = find(F, cp);
        if (!g) continue;                     /* missing glyph draws nothing, never a box */
        x += draw_glyph(x, y, g, F, fg, bg);
    }
    return x - x0;
}
int gfx_text_w(const char *s, gfx_font f) {
    fontref F = fref(f);
    int w = 0; unsigned cp;
    while (*s) { s = u8(s, &cp); const ns_glyph *g = find(F, cp); if (g) w += g->w; }
    return w;
}
int gfx_text_ellipsis(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg, int maxw) {
    if (gfx_text_w(s, f) <= maxw) return gfx_text(x, y, s, f, fg, bg);
    fontref F = fref(f);
    int ew = gfx_text_w("...", f), w = 0, x0 = x; unsigned cp;
    const char *p = s;
    while (*p) {
        const char *nx = u8(p, &cp);
        const ns_glyph *g = find(F, cp);
        int gw = g ? g->w : 0;
        if (w + gw + ew > maxw) break;
        if (g) x += draw_glyph(x, y, g, F, fg, bg);
        w += gw; p = nx;
    }
    x += gfx_text(x, y, "...", f, fg, bg);
    return x - x0;
}

int gfx_text_wrap(int x, int y, const char *s, gfx_font f, uint16_t fg, uint16_t bg,
                  int maxw, int line_h, int draw) {
    fontref F = fref(f);
    int lines = 0;
    while (*s) {
        /* find the longest prefix that fits, breaking at the last space */
        const char *p = s, *lastsp = 0;
        int w = 0; unsigned cp;
        while (*p) {
            const char *nx = u8(p, &cp);
            const ns_glyph *g = find(F, cp);
            int gw = g ? g->w : 0;
            if (w + gw > maxw) break;
            if (cp == ' ') lastsp = p;
            w += gw; p = nx;
        }
        const char *end = *p ? (lastsp ? lastsp : p) : p;
        if (end == s) end = p;                /* a single word longer than the line: hard-break */
        if (draw) {
            int xx = x; const char *q = s;
            while (q < end) {
                q = u8(q, &cp);
                const ns_glyph *g = find(F, cp);
                if (g) xx += draw_glyph(xx, y + lines * line_h, g, F, fg, bg);
            }
        }
        lines++;
        s = end;
        while (*s == ' ') s++;
        if (lines > 200) break;               /* runaway guard */
    }
    return lines;
}
