#!/bin/sh
# Wrapper around Ndless's build_toolchain.sh for Apple Silicon / Homebrew.
#
# The upstream script's prerequisite check compiles `gcc -lgmp test.c`, which fails on macOS because
# Homebrew installs to /opt/homebrew and that is not on clang's default search path. zlib is
# additionally keg-only, so it needs its own -L/-I.
#
# BUT: putting /opt/homebrew/include on CPATH wholesale breaks the GCC build. Homebrew's gettext
# ships libintl.h there, which redefines setlocale and collides with GCC's own declaration -- libcpp
# fails with "expected unqualified-id" in every translation unit. So we expose ONLY the four headers
# GCC actually needs, via a symlink farm, and libintl.h stays invisible.
set -eu
BREW=/opt/homebrew
export LIBRARY_PATH="${BREW}/lib:${BREW}/opt/zlib/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
INCFARM="${INCFARM:-/tmp/ndinc}"
mkdir -p "${INCFARM}"
# COPY, do not symlink. GCC's configure canonicalises the header location it finds and records it
# as GMPINC; a symlink resolves straight back to ${BREW}/include, which puts the whole Homebrew
# prefix -- and therefore gettext's libintl.h -- back on every compile line. Copies have no path to
# resolve to.
for h in gmp.h gmpxx.h mpfr.h mpf2mpfr.h mpc.h; do
    [ -f "${BREW}/include/$h" ] && cp -f "${BREW}/include/$h" "${INCFARM}/$h"
done
for h in zlib.h zconf.h; do
    [ -f "${BREW}/opt/zlib/include/$h" ] && cp -f "${BREW}/opt/zlib/include/$h" "${INCFARM}/$h"
done
export CPATH="${INCFARM}${CPATH:+:$CPATH}"
export CPPFLAGS="-I${INCFARM}"   # NOT ${BREW}/include -- see the libintl note above
export LDFLAGS="-L${BREW}/lib -L${BREW}/opt/zlib/lib"
export LIBFARM_NOTE="headers are copied, not linked -- see above"
export PARALLEL="${PARALLEL:--j10}"

# newlib's libgloss builds documentation, which needs makeinfo. Missing makeinfo fails the whole
# libgloss target with Error 127 -- a doc-only failure that kills a library build. Homebrew's
# texinfo is keg-only so it is not on PATH by default; put it there, and set MAKEINFO=true as a
# fallback so a doc target can never again block the toolchain.
[ -d "${BREW}/opt/texinfo/bin" ] && export PATH="${BREW}/opt/texinfo/bin:${PATH}"
export MAKEINFO="${MAKEINFO:-true}"

# Upstream passes --disable-nls to binutils and newlib but NOT to GCC. On a machine with Homebrew's
# gettext installed, GCC's configure reports "whether to use NLS... yes", so libcpp/system.h takes
# its `#include <libintl.h>` branch. libcpp's own configure meanwhile leaves HAVE_SETLOCALE
# undefined, so system.h:275 has already defined `setlocale` as a function-like macro -- which then
# mangles libintl.h's own setlocale declaration and every libcpp translation unit dies with
# "expected unqualified-id".
#
# This is a property of the host having gettext installed, not of the target, so disabling NLS is
# the correct fix rather than a workaround. Patch is idempotent.
TC_SCRIPT="$(dirname "$0")/../vendor/Ndless/ndless-sdk/toolchain/build_toolchain.sh"
if ! grep -q 'OPTIONS_GCC=.*--disable-nls' "${TC_SCRIPT}"; then
    sed -i.orig 's|^OPTIONS_GCC="|OPTIONS_GCC="--disable-nls |' "${TC_SCRIPT}"
    echo "patched OPTIONS_GCC with --disable-nls"
fi

# After installing GCC stage 1, upstream deletes two autogenerated newlib headers it expects to have
# been copied in by --with-headers. With newlib 4.5.0 they are NOT present (newlib.h and
# _newlib_version.h are generated into newlib's BUILD dir, not shipped in newlib/libc/include), so
# the bare `rm` returns non-zero -- and build_toolchain.sh runs `set -eu`, so a cleanup line for a
# file that was never there kills the entire build immediately after a successful 40-minute GCC
# stage. Make those two removals tolerant. Idempotent.
if grep -q '^\trm "${PREFIX}/arm-none-eabi/sys-include/newlib.h"' "${TC_SCRIPT}"; then
    sed -i.orig2 's|^\(\t*\)rm "${PREFIX}/arm-none-eabi/sys-include/|\1rm -f "${PREFIX}/arm-none-eabi/sys-include/|' "${TC_SCRIPT}"
    echo "patched sys-include cleanup to rm -f"
fi

# Always leave a terminal marker, success OR failure. Without this the only way to tell a finished
# build from a dead one is to poll for compiler processes -- and a pgrep whose pattern appears in the
# watcher's own command line matches ITSELF, so the watcher waits forever on a build that died an
# hour ago. Learned the expensive way.
DONE_MARKER=/tmp/toolchain_build.done
rm -f "${DONE_MARKER}"
trap 'rc=$?; echo "=== toolchain build exit rc=${rc} ==="; echo "${rc}" > "${DONE_MARKER}"' EXIT

cd "$(dirname "$0")/../vendor/Ndless/ndless-sdk/toolchain"
echo "=== toolchain build start: $(date) ==="
echo "PARALLEL=${PARALLEL}  LIBRARY_PATH=${LIBRARY_PATH}"
./build_toolchain.sh
echo "=== toolchain build end: $(date) ==="
