#!/usr/bin/env python3
"""Pre-render a proportional anti-aliased bitmap font for the device.

WHY BITMAP, NOT FREETYPE AT RUNTIME: the model already takes 7.5 MB of a 21 MB heap, and FreeType
plus a TTF would add both binary size and per-glyph rasterisation cost on a 396 MHz core with no
FPU. Rasterising once on the host costs nothing at run time and the whole table is ~40 KB.

4 bits per pixel of coverage (16 levels) is enough for clean anti-aliasing against a white ground
and halves the table against 8bpp. Glyphs are packed row-major, two pixels per byte.

Covers Latin-1 plus the Greek letters and maths symbols the notation needs -- if a glyph the
renderer asks for is missing it draws nothing, so the coverage set is the contract.
"""
import sys, pathlib
from PIL import Image, ImageFont, ImageDraw

FONT = "/System/Library/Fonts/Supplemental/Arial.ttf"
BOLD = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"

# PER-GLYPH FALLBACK. Arial has no subscript digits and only three superscripts, and Pillow
# substitutes the missing-glyph BOX rather than failing -- so the first version of this font shipped
# 18 tofu boxes that were indistinguishable from real glyphs by any check on width or ink. On screen
# "lambda_0" rendered as "λ□". Arial Unicode is the same design extended, so a glyph taken from it
# sits beside an Arial glyph without looking borrowed.
FALLBACK = "/System/Library/Fonts/Supplemental/Arial Unicode.ttf"

# what the UI and the notation renderer actually draw
CHARS = [chr(c) for c in range(32, 127)]
CHARS += list("°±×÷·−–—‘’“”…≤≥≈∞√∫Δ∂ΩμπλθαβγδεφσωρτηνξψχΣΠ₀₁₂₃₄₅₆₇₈₉⁰¹²³⁴⁵⁶⁷⁸⁹⁻")

def _bitmap(f, ch, w, height):
    img = Image.new("L", (max(w, 1), height), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=f, fill=255)
    return img

def _is_tofu(f, ch, height):
    """True when the face lacks `ch` and Pillow drew its missing-glyph box.

    Detected by COMPARING PIXELS against a code point no face has (U+FFFF). Checking width or ink
    does not work: the box has both, which is exactly how 18 of them shipped unnoticed."""
    ref_w = int(round(f.getlength("\uffff")))
    if ref_w <= 0:
        return False
    w = int(round(f.getlength(ch)))
    if w != ref_w:
        return False
    return _bitmap(f, ch, w, height).tobytes() == _bitmap(f, "\uffff", ref_w, height).tobytes()

def render(path, size, name, out):
    f = ImageFont.truetype(path, size)
    fb = ImageFont.truetype(FALLBACK, size)
    asc, desc = f.getmetrics()
    height = asc + desc
    glyphs = []
    borrowed = []
    for ch in CHARS:
        src = f
        if _is_tofu(f, ch, height):
            if _is_tofu(fb, ch, height):
                # NEITHER face has it. Emit nothing at all: gfx_text skips an absent glyph, and a
                # character that is missing is better than one that is a lie.
                glyphs.append((ch, 0, b"")); continue
            src, _ = fb, borrowed.append(ch)
        w = int(round(src.getlength(ch)))
        if w <= 0:
            glyphs.append((ch, 0, b"")); continue
        img = _bitmap(src, ch, w, height)
        px = img.load()
        # 4bpp, two pixels per byte, row-major
        data = bytearray()
        for y in range(height):
            for x in range(0, w, 2):
                hi = px[x, y] >> 4
                lo = (px[x + 1, y] >> 4) if x + 1 < w else 0
                data.append((hi << 4) | lo)
        glyphs.append((ch, w, bytes(data)))

    if borrowed:
        print(f"  {name}: {len(borrowed)} glyph(s) taken from Arial Unicode: {''.join(borrowed)}")
    dropped = [c for c, w, d in glyphs if w == 0]
    if dropped:
        print(f"  {name}: {len(dropped)} glyph(s) in NEITHER face, emitted as absent: {''.join(dropped)}")

    lines = [f"/* {name}: Arial {size}px, 4bpp coverage. Generated by tools/mkfont.py -- do not edit. */",
             f"#define {name}_H {height}", f"#define {name}_ASC {asc}",
             f"static const unsigned char {name}_DATA[] = {{"]
    blob, index = bytearray(), []
    for ch, w, data in glyphs:
        index.append((ord(ch), w, len(blob), len(data)))
        blob += data
    for i in range(0, len(blob), 16):
        lines.append("  " + ",".join(str(b) for b in blob[i:i+16]) + ",")
    lines.append("};")
    lines.append(f"static const ns_glyph {name}_IDX[] = {{")
    # find() binary-searches this table, so it MUST be code-point ordered. mkfont emitted it in
    # CHARS order, which is not sorted -- the search would silently miss glyphs.
    index.sort(key=lambda r: r[0])
    for cp, w, off, ln in index:
        lines.append(f"  {{{cp},{w},{off},{ln}}},")
    lines.append("};")
    lines.append(f"#define {name}_N ((int)(sizeof {name}_IDX / sizeof {name}_IDX[0]))")
    out.write_text("\n".join(lines) + "\n")
    return height, len(blob), len(index)

if __name__ == "__main__":
    hdr = pathlib.Path("src/store/font_data.h")
    parts = ["#ifndef NS_FONT_DATA_H\n#define NS_FONT_DATA_H",
             "typedef struct { unsigned short cp; unsigned char w; unsigned int off; unsigned short len; } ns_glyph;"]
    tmp = pathlib.Path("/tmp/_f.h")
    total = 0
    for path, size, name in ((FONT, 13, "FONT_UI"), (BOLD, 13, "FONT_UIB"), (FONT, 15, "FONT_BIG")):
        h, blob, n = render(path, size, name, tmp)
        parts.append(tmp.read_text())
        total += blob
        print(f"  {name:9} {size}px  height {h}  {n} glyphs  {blob/1024:.1f} KB")
    parts.append("#endif")
    hdr.write_text("\n".join(parts))
    print(f"  -> {hdr}  total {total/1024:.1f} KB of glyph data")
